-- Enable Row Level Security (RLS) on the darkfeminine_reviews table
ALTER TABLE darkfeminine_reviews ENABLE ROW LEVEL SECURITY;

-- 1. Allow public read access
-- Anyone visiting the website needs to be able to see the reviews
CREATE POLICY "Allow public read access to reviews"
ON darkfeminine_reviews
FOR SELECT
USING (true);

-- 2. Allow authenticated users to update their own reviews
-- Users can only modify a review if their authenticated email matches the user_email on the review
CREATE POLICY "Allow users to update their own reviews"
ON darkfeminine_reviews
FOR UPDATE
USING (auth.jwt()->>'email' = user_email)
WITH CHECK (auth.jwt()->>'email' = user_email);

-- 3. Allow authenticated users to insert their own reviews
-- If they don't have one generated by the Edge Function, they can create one matching their email
CREATE POLICY "Allow users to insert their own reviews"
ON darkfeminine_reviews
FOR INSERT
WITH CHECK (auth.jwt()->>'email' = user_email);